spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Mexico_City
    locale: es_MX    
    serialization:
      fail-on-empty-beans: false
  config:
    activate:
      on-profile:
       default
  datasource:
    url: ${CADENA_CONEXION_DB_MSSPPA}
    username: ${USER_DB_MSSPPA}
    password: ${PASSWORD_DB_MSSPPA}
    ##driverClassName: org.mariadb.jdbc.Driver
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Mexico_City
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ##database-platform: org.hibernate.dialect.MariaDB103Dialect
    database-platform: org.hibernate.dialect.H2Dialect
server:
  servlet:
    contextPath: /mssppa-base/v1
  port: 8080
  
authorization:
  signingKey: ${SIGNING_KEY_OAUTH}

info:
  component: Microservicio  Funcionalidad Base para SPPA
logging:
  file:
    name: mssppa-base.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    mx.gob.imss.cit.sppa: ${MSSPPA_LOG_LEVEL}
    
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, env, beans, metrics, threaddump, vigencia, genericEndPoints
  endpoint:
    health:
      show-details: always
    security:
      enabled: false
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    ping:
      enabled: true
  info:
    git:
      mode: full
---
spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: America/Mexico_City
    locale: es_MX    
    serialization:
      fail-on-empty-beans: false
  config:
    activate:
      on-profile:
       local
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Mexico_City
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
server:
  servlet:
    contextPath: /mssppa-base/v1
  port: 9090
  
authorization:
  signingKey: algun_codigo_secreto_qwerty_pa_validar_token

info:
  component: Microservicio  Funcionalidad Base para SPPA
logging:
  file:
    name: mssppa-base.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    mx.gob.imss.cit.sppa: INFO
    
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, env, beans, metrics, threaddump, vigencia, genericEndPoints
  endpoint:
    health:
      show-details: always
    security:
      enabled: false
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    ping:
      enabled: true
  info:
    git:
      mode: full
