DROP TABLE IF EXISTS SSCC_DELEGACION;
CREATE TABLE SSCC_DELEGACION (
  CVE_DELEGACION BIGINT AUTO_INCREMENT  NOT NULL   PRIMARY KEY,
  DES_DELEGACION VARCHAR(30)  NULL,
  REF_ABREVIACION VARCHAR(3)  NULL,
  FEC_ALTA TIMESTAMP  NOT NULL  ,
  FEC_BAJA TIMESTAMP  NULL  NULL,
  FEC_MODIFICA TIMESTAMP  NULL  NULL,
  CVE_USUARIO_ALTA VARCHAR(60) NOT NULL,
  CVE_USUARIO_BAJA VARCHAR(60)  NULL,
  CVE_USUARIO_MODIFICA VARCHAR(60)  NULL
) ;